" Disable compatibility with vi which can cause unexpected issues.
set nocompatible

runtime! rc.d/*.vim

" Highlight cursor line underneath the cursor horizontally.
set cursorline

" Highlight cursor line underneath the cursor vertically.
set cursorcolumn

" While searching though a file incrementally highlight matching characters as you type.
set incsearch

" Ignore capital letters during search.
set ignorecase

" Override the ignorecase option if searching for capital letters.
" This will allow you to search specifically for capital letters.
set smartcase

" Show matching words during a search.
set showmatch

" Use highlighting when doing a search.
set hlsearch

" Show partial command you type in the last line of the screen.
set showcmd

" Show the mode you are on the last line.
set showmode

" Disable line wrapping
set nowrap

" Enable relative line number in Visual mode
nnoremap <silent> v :set relativenumber<CR>v
nnoremap <silent> V :set relativenumber<CR>V
nnoremap <silent> <c-v> :set relativenumber<CR><c-v>
vnoremap <silent> <esc> <esc>:set norelativenumber<CR>
vnoremap <silent> y y:set norelativenumber<CR>
vnoremap <silent> d d:set norelativenumber<CR>
vnoremap <silent> c c:set norelativenumber<CR>
vnoremap <silent> r r:set norelativenumber<CR>
vnoremap <silent> p p:set norelativenumber<CR>
vnoremap <silent> < <:set norelativenumber<CR>
vnoremap <silent> > >:set norelativenumber<CR>

" Enable auto completion menu after pressing TAB.
set wildmenu

" Make wildmenu behave like similar to Bash completion.
set wildmode=list:longest

" There are certain files that we would never want to edit with Vim.
" Wildmenu will ignore files with these extensions.
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx

" Type jj to exit insert mode quickly.
inoremap jj <Esc>

" Press the space bar to type the : character in command mode.
nnoremap <silent> <space> :YcmCompleter GoTo<CR>
nnoremap <silent> <C-@> :YcmCompleter GoToReferences<CR>

" Center the cursor vertically when moving to the next word during a search.
nnoremap n nzz
nnoremap N Nzz

" Yank from cursor to the end of line.
nnoremap Y y$

" Navigate the split view easier by pressing CTRL+j, CTRL+k, CTRL+h, or CTRL+l.
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l

" Enbale 'Solarazied' colorscheme
syntax enable
set background=dark
colorscheme solarized
